/**
 * `chat_sessions` + `agent_events` reads/writes (docs/08-chat-agent-webapp.md
 * §2.2 `store.ts`) — plain functions over an injected `Db` (the same
 * `BetterSQLite3Database<typeof schema>` shape as `db/instance.ts`'s
 * singleton), so tests can point them at an isolated in-memory database
 * instead of the real `db/instance.ts` (see test/agent/store.test.ts).
 */
import type { InferSelectModel } from 'drizzle-orm';
import { and, asc, eq, gt, max } from 'drizzle-orm';

import type { db as DbInstance } from '../db/instance.js';
import { agentEvents, chatSessions } from '../db/schema.js';

export type Db = typeof DbInstance;

export type ChatSessionRow = InferSelectModel<typeof chatSessions>;
export type ChatSessionStatus = ChatSessionRow['status'];
export type AgentEventRow = InferSelectModel<typeof agentEvents>;

// ---- chat_sessions ----

export interface CreateChatSessionInput {
  /**
   * Generated by the caller (`routes/chat.ts`), not here — the sandbox has
   * to be created (`sandboxManager.acquire`) under a name derived from this
   * same id *before* the row can be inserted, so the id has to exist first.
   */
  id: string;
  userId: string;
  title: string;
  repo: string;
  branchName: string;
  sandboxName: string;
}

export function createChatSession(
  db: Db,
  input: CreateChatSessionInput,
): ChatSessionRow {
  const now = new Date();
  const row: ChatSessionRow = {
    id: input.id,
    userId: input.userId,
    title: input.title,
    repo: input.repo,
    branchName: input.branchName,
    sandboxName: input.sandboxName,
    status: 'active',
    lastActiveAt: now,
    nimboStateJson: null,
    createdAt: now,
  };
  db.insert(chatSessions).values(row).run();
  return row;
}

export function listChatSessions(db: Db, userId: string): ChatSessionRow[] {
  return db
    .select()
    .from(chatSessions)
    .where(eq(chatSessions.userId, userId))
    .orderBy(asc(chatSessions.createdAt))
    .all();
}

export function getChatSession(
  db: Db,
  id: string,
  userId: string,
): ChatSessionRow | undefined {
  return db
    .select()
    .from(chatSessions)
    .where(and(eq(chatSessions.id, id), eq(chatSessions.userId, userId)))
    .get();
}

export interface ChatSessionPatch {
  status?: ChatSessionStatus;
  nimboStateJson?: string;
  lastActiveAt?: Date;
}

export function updateChatSession(
  db: Db,
  id: string,
  patch: ChatSessionPatch,
): void {
  db.update(chatSessions).set(patch).where(eq(chatSessions.id, id)).run();
}

// ---- agent_events ----

/** Seq continuation point for a session (docs/08 §2.2 "seq 单调，从 DB max(seq) 续") — `0` if the session has no events yet, so the first appended event is `seq = 1`. */
export function getMaxEventSeq(db: Db, sessionId: string): number {
  const row = db
    .select({ value: max(agentEvents.seq) })
    .from(agentEvents)
    .where(eq(agentEvents.sessionId, sessionId))
    .get();
  return row?.value ?? 0;
}

export interface AppendAgentEventInput {
  sessionId: string;
  seq: number;
  type: string;
  payloadJson: string;
}

export function appendAgentEvent(
  db: Db,
  input: AppendAgentEventInput,
): AgentEventRow {
  const row: AgentEventRow = {
    sessionId: input.sessionId,
    seq: input.seq,
    ts: new Date(),
    type: input.type,
    payloadJson: input.payloadJson,
  };
  db.insert(agentEvents).values(row).run();
  return row;
}

/** Replay, in arrival order; `afterSeq` (exclusive) drives `GET .../events?after=<seq>` pagination (docs/08 §2.2). */
export function listAgentEvents(
  db: Db,
  sessionId: string,
  afterSeq?: number,
): AgentEventRow[] {
  const condition =
    afterSeq !== undefined ?
      and(eq(agentEvents.sessionId, sessionId), gt(agentEvents.seq, afterSeq))
    : eq(agentEvents.sessionId, sessionId);
  return db
    .select()
    .from(agentEvents)
    .where(condition)
    .orderBy(asc(agentEvents.seq))
    .all();
}
