/**
 * `conversations` 这张表的读写——纯函数 + 注入的 `Db`，所以测试可以指向一个隔离的内存
 * 数据库而不是 `db/instance.ts` 的单例（见 test/agent/store.test.ts）。
 *
 * **[账本](../../../../docs/terms.md)、[裁决表](../../../../docs/terms.md)、
 * [待发队列](../../../../docs/terms.md)、[起轮标记](../../../../docs/terms.md)不在这里**
 * ——它们是 `@nimbo/agent` 的宿主能力接口，实现落在 `persistence.ts`。本文件只剩
 * chat 应用自己的那些列：标题、仓库、分支、沙盒 provider/名字、[skill 清单](../../../../docs/terms.md)缓存。
 */
import type { InferSelectModel } from 'drizzle-orm';
import { and, asc, eq } from 'drizzle-orm';
import { z } from 'zod';

import type { db as DbInstance } from '../db/instance.js';
import { conversationEvents, conversations } from '../db/schema.js';
import type { Logger } from '../logger.js';
import { logger as defaultLogger } from '../logger.js';
import type { SkillSummaryDto } from '../schemas/chat.js';
import { SkillSummarySchema } from '../schemas/chat.js';

const LOG_SCOPE = 'store';

export type Db = typeof DbInstance;

export type ConversationRow = InferSelectModel<typeof conversations>;
export type ConversationStatus = ConversationRow['status'];
export type ConversationEventRow = InferSelectModel<typeof conversationEvents>;
export type ConversationEventKind = ConversationEventRow['kind'];

// ---- conversations ----

export interface CreateConversationInput {
  /**
   * Generated by the caller (`routes/chat.ts`), not here — the sandbox has
   * to be created (`sandboxManager.acquire`) under a name derived from this
   * same id *before* the row can be inserted, so the id has to exist first.
   */
  id: string;
  userId: string;
  title: string;
  repo: string;
  branchName: string;
  sandboxName: string;
  /** 沙盒 provider（docs/tech/sandbox-provider.md）。省略时默认 `'vercel'`，与列默认一致——路由侧始终显式传，省略仅便于测试夹具。 */
  provider?: ConversationRow['provider'];
  /** E2B 的[重连令牌](docs/terms.md) sandboxId（建盒后由路由回填）；Vercel/建会话初始为 null。 */
  sandboxId?: string | null;
}

export function createConversation(
  db: Db,
  input: CreateConversationInput,
): ConversationRow {
  const now = new Date();
  const row: ConversationRow = {
    id: input.id,
    userId: input.userId,
    title: input.title,
    repo: input.repo,
    branchName: input.branchName,
    sandboxName: input.sandboxName,
    provider: input.provider ?? 'vercel',
    sandboxId: input.sandboxId ?? null,
    status: 'active',
    lastActiveAt: now,
    agentSessionId: null,
    agentSessionCreatedAt: null,
    agentSessionTurn: null,
    queuedMessagesJson: '[]', // 空[待发队列](../../../../docs/terms.md)，与列默认值一致
    availableSkillsJson: '[]', // 空 [skill 清单](../../../../docs/terms.md)——沙盒就绪后首次填上
    turnHolder: null, // [起轮标记](../../../../docs/terms.md)：没有轮在跑
    turnStartedAt: null,
    createdAt: now,
  };
  db.insert(conversations).values(row).run();
  return row;
}

export function listConversations(db: Db, userId: string): ConversationRow[] {
  return db
    .select()
    .from(conversations)
    .where(eq(conversations.userId, userId))
    .orderBy(asc(conversations.createdAt))
    .all();
}

export function getConversation(
  db: Db,
  id: string,
  userId: string,
): ConversationRow | undefined {
  return db
    .select()
    .from(conversations)
    .where(and(eq(conversations.id, id), eq(conversations.userId, userId)))
    .get();
}

/**
 * 不带属主过滤的按 id 读——**只给系统级路径用**（`runtime.ts` 的
 * [起轮装配](../../../../docs/terms.md)：这一轮可能是[自动出队](../../../../docs/terms.md)
 * 起的，此刻没有请求上下文，属主校验早在入队那次请求里做过了）。
 *
 * 请求路径上一律用 `getConversation(db, id, userId)`——不存在与不属于自己都回 404，
 * 不泄露存在性。
 */
export function getConversationById(
  db: Db,
  id: string,
): ConversationRow | undefined {
  return db.select().from(conversations).where(eq(conversations.id, id)).get();
}

export interface ConversationPatch {
  status?: ConversationStatus;
  lastActiveAt?: Date;
  /** E2B 的[重连令牌](docs/terms.md) sandboxId——首建落库、或过期重建后换了新 sandbox 时由路由回写（docs/tech/sandbox-provider.md §3.1）。 */
  sandboxId?: string;
  /**
   * The nimbo session-scalar header (docs/tech/single-ledger.md §5 单-3, schema.ts's own doc
   * comment) — all three always written together, at the end of every turn
   * that finishes gracefully (`@nimbo/agent`'s `finalize`).
   * There is no partial-update case, so this is one combined optional group
   * rather than three independent optional fields.
   */
  agentSessionHeader?: {
    conversationId: string;
    createdAt: Date;
    turn: number;
  };
}

export function updateConversation(
  db: Db,
  id: string,
  patch: ConversationPatch,
): void {
  const { agentSessionHeader, ...rest } = patch;
  db.update(conversations)
    .set({
      ...rest,
      ...(agentSessionHeader !== undefined ?
        {
          agentSessionId: agentSessionHeader.conversationId,
          agentSessionCreatedAt: agentSessionHeader.createdAt,
          agentSessionTurn: agentSessionHeader.turn,
        }
      : {}),
    })
    .where(eq(conversations.id, id))
    .run();
}

/** 同 `queuedMessagesSchema`：JSON 列的反序列化边界（docs/tech/composer-skill-mention.md §3）。 */
const availableSkillsSchema = z.array(SkillSummarySchema);

/**
 * `available_skills_json` 列 → `SkillSummary[]`（[skill 清单](../../../../docs/terms.md)）。
 *
 * 列内容损坏时**当作空清单**并记一行 warn，与 `agent/persistence.ts` 的 `parseQueuedInputs` 同一取舍——
 * 清单只是给 [composer](../../../../docs/terms.md) 列菜单用的缓存，不该让一次
 * `GET .../conversations` 因为它而 500。菜单空着时用户仍能正常发消息，agent 也
 * 照常能用 skill（`buildSession` 自己扫沙盒，不读这一列）。
 *
 * 单独导出的理由同 `parseQueuedInputs`：路由已把整行 `select` 出来了，直接解析
 * 手上这一列比再查一次库便宜。
 */
export function parseAvailableSkills(
  json: string,
  conversationId: string,
  log: Logger = defaultLogger,
): SkillSummaryDto[] {
  let parsedJson: unknown;
  try {
    parsedJson = JSON.parse(json);
  } catch (error) {
    log.warn(LOG_SCOPE, 'available skills column is not valid JSON', {
      conversationId,
      error: error instanceof Error ? error.message : String(error),
    });
    return [];
  }

  const result = availableSkillsSchema.safeParse(parsedJson);
  if (!result.success) {
    log.warn(LOG_SCOPE, 'available skills column failed validation', {
      conversationId,
      error: result.error.message,
    });
    return [];
  }
  return result.data;
}

/**
 * 刷新 [skill 清单](../../../../docs/terms.md)缓存，**内容没变就不写**
 * （docs/tech/composer-skill-mention.md §2.1）。返回落库的 JSON，调用方可直接拿去
 * 拼 DTO，不必再查一次库。
 *
 * 调用点两处：会话创建时沙盒首次就绪（`routes/chat.ts`）、以及每轮
 * [起轮装配](../../../../docs/terms.md)（`agent/runtime.ts` 的 `prepareTurn`）。后者是每轮必经路径，
 * 而清单绝大多数轮次纹丝不动——所以这里**由调用方把手上已有的当前值传进来**
 * （`ConversationRow.availableSkillsJson`，起轮时早就 select 出来了）做一次字符串
 * 比对，零额外查询地省掉那次无谓 `UPDATE`。
 *
 * 比对的是 `JSON.stringify` 后的字符串而不是深比较：清单来自
 * `loadSkillsFromWorkspace`，那边已经按名字典序排过，同样的沙盒内容必然产出逐字节
 * 相同的 JSON，字符串比对足够且更便宜。
 *
 * 覆盖语义、无合并：清单是「此刻沙盒里有什么」的快照。会话行不存在时
 * `UPDATE ... WHERE id = ?` 匹配零行，静默 no-op——写缓存失败不该让起轮失败。
 */
export function syncAvailableSkills(
  db: Db,
  conversationId: string,
  currentJson: string,
  skills: readonly SkillSummaryDto[],
): string {
  const nextJson = JSON.stringify(skills);
  if (nextJson === currentJson) {
    return currentJson;
  }
  db.update(conversations)
    .set({ availableSkillsJson: nextJson })
    .where(eq(conversations.id, conversationId))
    .run();
  return nextJson;
}
